spring:
  # MariaDB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/insta
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      password:
        visible: true

  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080
  servlet:
    session:
      timeout: 3600
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
  tomcat:
    use-relative-redirects: true

logging.level:
  org.springframework.security: TRACE
